// <auto-generated />
using System;
using AppMapas.Infraestructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AppMapas.Migrations
{
    [DbContext(typeof(DepartmentDbContext))]
    [Migration("20201022145455_BaseDeDatosInicial")]
    partial class BaseDeDatosInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AppMapas.Domain.Barrio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(40) CHARACTER SET utf8mb4")
                        .HasMaxLength(40);

                    b.Property<Guid>("_idMunicipio")
                        .HasColumnName("municipioId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("_idMunicipio");

                    b.ToTable("Barrio");
                });

            modelBuilder.Entity("AppMapas.Domain.Departamento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(40) CHARACTER SET utf8mb4")
                        .HasMaxLength(40);

                    b.HasKey("Id");

                    b.ToTable("Departamento");
                });

            modelBuilder.Entity("AppMapas.Domain.Municipio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(40) CHARACTER SET utf8mb4")
                        .HasMaxLength(40);

                    b.Property<Guid>("_idDepartamento")
                        .HasColumnName("departamentoId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("_idDepartamento");

                    b.ToTable("Municipio");
                });

            modelBuilder.Entity("AppMapas.Domain.Barrio", b =>
                {
                    b.HasOne("AppMapas.Domain.Municipio", "Municipio")
                        .WithMany()
                        .HasForeignKey("_idMunicipio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AppMapas.Domain.Municipio", b =>
                {
                    b.HasOne("AppMapas.Domain.Departamento", "Departamento")
                        .WithMany()
                        .HasForeignKey("_idDepartamento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
